plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

#CLAUDE: Do not change this
Metrics/ClassLength:
  Max: 100

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'imago_mcp_server.rb'

#CLAUDE: Do not change this
Metrics/AbcSize:
  Max: 5
  Exclude:
    - 'spec/**/*'

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 30

RSpec/NestedGroups:
  Max: 4
