plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.0
  NewCops: enable
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Max: 250

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'imago_mcp_server.rb'

Metrics/AbcSize:
  Max: 25

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 25

RSpec/NestedGroups:
  Max: 4
